SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# the size of the player ship
PLAYER_RADIUS = 20
# width of the lines to draw the player with
LINE_WIDTH = 2

PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS